# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99ba48f56d572daf666886f1f1a34dede606fbe32a1c96bfb7150be752f3fe204107f4b09a182a939e2a141286e1f9855f8b57a7a157734a1431fcdd878d4ecd

test:
  secret_key_base: e884dee18be421ffd066c2392d7c2231b5ba3877d1b2a45ed92967a6dd1a84f23d4122ad935c31f7a7edf7997b6435f336dfbddbd469e5bba7ec7bbc70365843

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
